/**
 * Two-Loop Business Workflow Architecture Enums
 * Authoritative source of truth for Business Transaction states and categories.
 */

export enum WorkflowState {
  // Loop 1: Manufacturing Workflow
  DRAFT = 'DRAFT',
  DESIGN_COMPLETED = 'DESIGN_COMPLETED',
  STORES_PROCESSING = 'STORES_PROCESSING',
  MATERIALS_ISSUED = 'MATERIALS_ISSUED',
  PRODUCTION_PROCESSING = 'PRODUCTION_PROCESSING',
  PRODUCTION_COMPLETED = 'PRODUCTION_COMPLETED',

  // Loop 2: Financial Workflow & Archival
  ACCOUNTS_COST_VERIFICATION = 'ACCOUNTS_COST_VERIFICATION',
  ACTUAL_COST_UPDATED = 'ACTUAL_COST_UPDATED',
  ACCOUNTS_FINANCIAL_CLOSURE = 'ACCOUNTS_FINANCIAL_CLOSURE',
  ARCHIVED = 'ARCHIVED',
  COMPLETED = 'COMPLETED',
}

export enum WorkflowLoop {
  MANUFACTURING_LOOP = 'MANUFACTURING_LOOP',
  FINANCIAL_LOOP = 'FINANCIAL_LOOP',
}

export enum CostSheetStatus {
  DRAFT = 'DRAFT',
  FINALIZED = 'FINALIZED',
  CANCELLED = 'CANCELLED',
}

export enum VendorProcessType {
  IN_HOUSE = 'IN_HOUSE',
  OUTSOURCED_VENDOR = 'OUTSOURCED_VENDOR',
}

export enum IndentPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum FileType {
  PDF = 'PDF',
  DRAWING = 'DRAWING',
  CAD = 'CAD',
  IMAGE = 'IMAGE',
  EXCEL = 'EXCEL',
  OTHER = 'OTHER',
}

export enum NotificationEventType {
  BUSINESS_TRANSACTION_SUBMITTED = 'BUSINESS_TRANSACTION_SUBMITTED',
  STORES_MATERIAL_ISSUED = 'STORES_MATERIAL_ISSUED',
  PRODUCTION_COMPLETED = 'PRODUCTION_COMPLETED',
  ACCOUNTS_COST_VERIFIED = 'ACCOUNTS_COST_VERIFIED',
  ACCOUNTS_FINANCIAL_CLOSED = 'ACCOUNTS_FINANCIAL_CLOSED',
  TRANSACTION_ARCHIVED = 'TRANSACTION_ARCHIVED',
  TRANSACTION_COMPLETED = 'TRANSACTION_COMPLETED',
}

export enum AuditEventType {
  CREATE_DRAFT = 'CREATE_DRAFT',
  SUBMIT_DESIGN = 'SUBMIT_DESIGN',
  STORES_ISSUE = 'STORES_ISSUE',
  PRODUCTION_UPDATE = 'PRODUCTION_UPDATE',
  VERIFY_COSTS = 'VERIFY_COSTS',
  FINANCIAL_CLOSURE = 'FINANCIAL_CLOSURE',
  ARCHIVE_TRANSACTION = 'ARCHIVE_TRANSACTION',
}
