export enum AppPermission {
  USERS_VIEW = 'users.view',
  USERS_CREATE = 'users.create',
  USERS_UPDATE = 'users.update',
  USERS_DELETE = 'users.delete',
  USERS_STATUS_UPDATE = 'users.status.update',
  USERS_RESTORE = 'users.restore',
  ROLES_VIEW = 'roles.view',
  ROLES_CREATE = 'roles.create',
  ROLES_UPDATE = 'roles.update',
  ROLES_DELETE = 'roles.delete',
  PERMISSIONS_VIEW = 'permissions.view',
  PERMISSIONS_CREATE = 'permissions.create',
  PERMISSIONS_UPDATE = 'permissions.update',
  PERMISSIONS_DELETE = 'permissions.delete',
  DEPARTMENTS_VIEW = 'departments.view',
  DEPARTMENTS_CREATE = 'departments.create',
  DEPARTMENTS_UPDATE = 'departments.update',
  DEPARTMENTS_DELETE = 'departments.delete',
  PRODUCTS_VIEW = 'products.view',
  PRODUCTS_CREATE = 'products.create',
  PRODUCTS_UPDATE = 'products.update',
  PRODUCTS_DELETE = 'products.delete',
  PRODUCTS_RESTORE = 'products.restore',
  MATERIALS_VIEW = 'materials.view',
  MATERIALS_CREATE = 'materials.create',
  MATERIALS_UPDATE = 'materials.update',
  MATERIALS_DELETE = 'materials.delete',
  PROCESSES_VIEW = 'manufacturing-processes.view',
  PROCESSES_CREATE = 'manufacturing-processes.create',
  PROCESSES_UPDATE = 'manufacturing-processes.update',
  PROCESSES_DELETE = 'manufacturing-processes.delete',
  PROCESSES_RESTORE = 'manufacturing-processes.restore',
  UNITS_VIEW = 'units.view',
  UNITS_CREATE = 'units.create',
  UNITS_UPDATE = 'units.update',
  UNITS_DELETE = 'units.delete',
  UNITS_RESTORE = 'units.restore',
  VENDORS_VIEW = 'vendors.view',
  VENDORS_CREATE = 'vendors.create',
  VENDORS_UPDATE = 'vendors.update',
  VENDORS_DELETE = 'vendors.delete',
  VENDORS_RESTORE = 'vendors.restore',
  INDENT_VIEW = 'indent.view',
  INDENT_CREATE = 'indent.create',
  INDENT_EDIT = 'indent.edit',
  INDENT_SUBMIT = 'indent.submit',
  INDENT_DELETE = 'indent.delete',
  COSTSHEET_VIEW = 'costsheet.view',
  COSTSHEET_CREATE = 'costsheet.create',
  COSTSHEET_UPDATE = 'costsheet.update',
  WORKFLOW_VIEW = 'workflow.view',
  STORES_ISSUE = 'stores.issue',
  PRODUCTION_VIEW = 'production.view',
  PRODUCTION_RECEIVE = 'production.receive',
  PRODUCTION_UPDATE = 'production.update',
  PRODUCTION_DELIVER = 'production.deliver',
  ACCOUNTS_VIEW = 'accounts.view',
  ACCOUNTS_VERIFY = 'accounts.verify',
  ACCOUNTS_CLOSE = 'accounts.close',
  SYSTEM_ARCHIVE = 'system.archive',
  SYSTEM_COMPLETE = 'system.complete',
  INVENTORY_VIEW = 'inventory.view',
  INVENTORY_ISSUE = 'inventory.issue',
  REPORTS_VIEW = 'reports.view',
  REPORTS_EXPORT = 'reports.export',
  ANALYTICS_VIEW = 'analytics.view',
  NOTIFICATIONS_VIEW = 'notifications.view',
  AUDIT_VIEW = 'audit.view',
  SETTINGS_MANAGE = 'settings.manage',
}

export const MODULE_PERMISSIONS: Record<string, AppPermission[]> = {
  users: [
    AppPermission.USERS_VIEW,
    AppPermission.USERS_CREATE,
    AppPermission.USERS_UPDATE,
    AppPermission.USERS_DELETE,
    AppPermission.USERS_STATUS_UPDATE,
    AppPermission.USERS_RESTORE,
  ],
  roles: [
    AppPermission.ROLES_VIEW,
    AppPermission.ROLES_CREATE,
    AppPermission.ROLES_UPDATE,
    AppPermission.ROLES_DELETE,
  ],
  indent: [
    AppPermission.INDENT_VIEW,
    AppPermission.INDENT_CREATE,
    AppPermission.INDENT_EDIT,
    AppPermission.INDENT_SUBMIT,
    AppPermission.INDENT_DELETE,
  ],
  costsheet: [
    AppPermission.COSTSHEET_VIEW,
    AppPermission.COSTSHEET_CREATE,
    AppPermission.COSTSHEET_UPDATE,
  ],
  workflow: [AppPermission.WORKFLOW_VIEW],
  production: [
    AppPermission.PRODUCTION_VIEW,
    AppPermission.PRODUCTION_RECEIVE,
    AppPermission.PRODUCTION_UPDATE,
    AppPermission.PRODUCTION_DELIVER,
  ],
  stores: [AppPermission.STORES_ISSUE],
  accounts: [
    AppPermission.ACCOUNTS_VIEW,
    AppPermission.ACCOUNTS_VERIFY,
    AppPermission.ACCOUNTS_CLOSE,
  ],
  system: [AppPermission.SYSTEM_ARCHIVE, AppPermission.SYSTEM_COMPLETE],
  inventory: [AppPermission.INVENTORY_VIEW, AppPermission.INVENTORY_ISSUE],
  reports: [AppPermission.REPORTS_VIEW, AppPermission.REPORTS_EXPORT],
  materials: [
    AppPermission.MATERIALS_VIEW,
    AppPermission.MATERIALS_CREATE,
    AppPermission.MATERIALS_UPDATE,
    AppPermission.MATERIALS_DELETE,
  ],
  products: [
    AppPermission.PRODUCTS_VIEW,
    AppPermission.PRODUCTS_CREATE,
    AppPermission.PRODUCTS_UPDATE,
  ],
  'manufacturing-processes': [
    AppPermission.PROCESSES_VIEW,
    AppPermission.PROCESSES_CREATE,
    AppPermission.PROCESSES_UPDATE,
    AppPermission.PROCESSES_DELETE,
    AppPermission.PROCESSES_RESTORE,
  ],
  units: [
    AppPermission.UNITS_VIEW,
    AppPermission.UNITS_CREATE,
    AppPermission.UNITS_UPDATE,
    AppPermission.UNITS_DELETE,
    AppPermission.UNITS_RESTORE,
  ],
  vendors: [
    AppPermission.VENDORS_VIEW,
    AppPermission.VENDORS_CREATE,
    AppPermission.VENDORS_UPDATE,
    AppPermission.VENDORS_DELETE,
    AppPermission.VENDORS_RESTORE,
  ],
  notifications: [AppPermission.NOTIFICATIONS_VIEW],
  analytics: [AppPermission.ANALYTICS_VIEW],
  settings: [AppPermission.SETTINGS_MANAGE],
};
