import React from 'react';
import { useAuthStore } from '../../store/authStore';

export interface PrintHeaderProps {
  moduleName: string;
  reportTitle: string;
  documentNumber?: string;
  subtitle?: string;
  customMetadata?: Array<{ label: string; value: string }>;
}

export const PrintHeader: React.FC<PrintHeaderProps> = ({
  moduleName,
  reportTitle,
  documentNumber,
  subtitle,
  customMetadata = [],
}) => {
  const user = useAuthStore((s) => s.user);
  const now = new Date();
  const formattedDate = now.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
  const formattedTime = now.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });

  const userName = user
    ? `${user.firstName || ''} ${user.lastName || ''}`.trim() || user.email
    : 'System User';
  const userDept = user?.department?.departmentName || user?.role?.roleName || 'MERC Operations';

  return (
    <div className="border-b-2 border-gray-800 pb-4 mb-5 print-break-inside-avoid">
      <div className="flex justify-between items-start">
        {/* Company Branding */}
        <div>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded bg-gray-900 text-white font-black text-base flex items-center justify-center tracking-tighter">
              M
            </div>
            <div>
              <h1 className="text-xl font-extrabold tracking-tight text-gray-950 uppercase leading-none">
                MERC
              </h1>
              <p className="text-[9px] uppercase tracking-wider font-semibold text-gray-600 mt-0.5">
                Manufacturing Enterprise Resource & Costing
              </p>
            </div>
          </div>
        </div>

        {/* Document Classification & Timestamp */}
        <div className="text-right text-[10px] text-gray-600 space-y-0.5">
          <p className="font-semibold text-gray-900">CONFIDENTIAL BUSINESS DOCUMENT</p>
          <p>
            Generated:{' '}
            <span className="font-medium text-gray-800">
              {formattedDate} at {formattedTime}
            </span>
          </p>
          <p>
            Generated By:{' '}
            <span className="font-medium text-gray-800">
              {userName} ({userDept})
            </span>
          </p>
        </div>
      </div>

      {/* Module Title Banner */}
      <div className="mt-4 pt-3 border-t border-gray-200 flex justify-between items-end">
        <div>
          <p className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">
            {moduleName}
          </p>
          <h2 className="text-lg font-bold text-gray-900 leading-tight">{reportTitle}</h2>
          {subtitle && <p className="text-xs text-gray-600 mt-0.5">{subtitle}</p>}
        </div>
        {documentNumber && (
          <div className="text-right">
            <p className="text-[9px] uppercase font-bold text-gray-500 tracking-wider">
              Document No.
            </p>
            <p className="text-sm font-mono font-bold text-gray-900">{documentNumber}</p>
          </div>
        )}
      </div>

      {/* Custom Metadata Bar if provided */}
      {customMetadata.length > 0 && (
        <div className="mt-3 pt-2 border-t border-gray-100 grid grid-cols-2 md:grid-cols-4 gap-3 text-xs">
          {customMetadata.map((meta, i) => (
            <div key={i}>
              <span className="text-gray-500 block text-[9px] uppercase font-semibold">
                {meta.label}
              </span>
              <span className="font-medium text-gray-900">{meta.value || '—'}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
